** TODO [#A] Database of File Types/Categories and their Operations
   Sources in [[file:pnw-files-ops.el]], [[file:emdb.el]], [[file:pnw-fstree.el]]
*** TODO [#A] Call query-replace-regexp-in-directory-tree with dmatcher and fmatcher generated by emdb-build-name-regexp() in emdb.el
*** Search
    - Use =with-temp-buffer()= and =insert-file-contents()= to open and
      =re-search-forward()= to gather the hits. This allows us to grep for
      multi-line regexps.
    - If no syntax-context (see [[elisp:read-syntax-context()]]) is given and the
      file is not compressed we can call =insert-file-contents-literally()=
      instead to speed up things.
    - Also first see how *occur-mode* does it.
    - Use =tv-find-all-regex-in-file()= which reads file into a list of
      line-strings.
*** Other
    - *Integrate* and remove file:~/pnw/emacs/run-assoc.el.
    - *Maybe Integrate* file:~/elisp/file-props.el.
    - *Integrate* with =auto-mode-alist= and =magic-mode-alist=.
    - *Generalize* the argument =fmatcher= of findr-scan() which can be
      either a *function* =functionp()= or a *regexp* =stringp()=.
    - If needed add another argument dmatcher that works like fmatcher but for files.
    - Then create a *function-generator* in emdb.el that creates this matcher function.
    - *Merge* [[file:~/pnw/emacs/mine/pnw-findr.el]] and [[file:~/pnw/emacs/mine/filedb.el]]
    - Compare *Performance* between =pnw-rfind= and =pnw-findr= and use the fastest.
    - Use =regexp-alt-list()= to build =findr-skip-directory-regexp= and
      =findr-skip-file-regexp= from lists. Merge regexps in file:pnw-findr.el
      and file:emdb.el into =emdb-table=. The include/exclude filters in
      file:pnw-findr.el are better given in the form
      - Include: (list 'c-header 'c-source)
      - Exclude: (list 'gtags 'ectags)
    - We then include/exclude a given filename by mapping these lists onto the
      function [[lisp:emdb-file-is-type(filename type-name)]] defined in [[emdb.el]].
      This unifies all the [[regexp:file-is-.*]] functions in [[file:filedb.el]].
    - Merge all variables [[regexp:.*-file-regexp]] in file:emdb.el into a common
      structure file-extension-table that is accessed with assoc().
    - *Merge* =pnw-all-subdirs()= with =findr()=.
    - *Merge* all functions file-is-.*() file-begin-is-.*() in
      file:pnw-file-ops.el by reusing logic from file:emdb.el into one
      function (with aliases) file-class/kind/category/type-p(filename &optional
      classifier)
    - Integrate with Emacs Lisp version of file(1)/libmagic database at
      http://www.gnuvola.org/data/.
